### ISSUE TITLE
Recruitor - search

### ISSUE THREAD

**Issue by Mingtianfang-Li** [Mingtianfang-Li/CommonAssessmentTool#1]

**Comment by Mingtianfang-Li** [comment]
For the recruiter search section.

**Comment by Amaizzzzz** [comment]
**Week 1: Requirements and Design**
Define API Requirements
- Finalize key features (search by name/ID, filtering by employment status and rating).
- Confirm basic error handling requirements.

Plan API Design
- Design basic API structure for searching and filtering candidates.
- Document input/output formats (e.g., HTTP methods, query parameters).

**Week 2: Backend Setup and Basic Search**
Database Setup
- Set up a minimal candidate database (name, ID, employment status, rating).

Implement Basic Search API
- Implement an API to search candidates by name or ID.
- Return "No candidates found" if no matches exist.

**Week 3: Filtering and Basic Error Handling**
Implement Filter API
- Implement filtering by employment status and candidate rating.

Basic Error Handling
- Implement error handling for no results and basic network issues.

**Week 4: Integration and Testing**
Integrate Search and Filter
- Combine search and filter functionality into one unified workflow.

Test Basic Functionality
- Perform tests for both the search and filter functionalities.
- Test edge cases like "No candidates found" and error handling.

**Week 5: Final Testing and Adjustments**
Optimize Queries (if needed)
- Optimize search and filter for basic performance with small datasets.

Final Testing
- Conduct final tests to ensure all acceptance criteria are met.

**Week 6: Submission Preparation**
Document API
- Write a brief documentation for the API endpoints and error handling.
Wrap-up
- Final review, code cleanup, and submission.

**Comment by Mingtianfang-Li** [comment]
Looks Good!
